### ISSUE TITLE
Vibration after scanning

### ISSUE THREAD

**Issue by JimTudeski** [id1945/ngx-scanner-qrcode#13]
hi,
as the sound "beep" it would be nice if the device vibrate after scanning.
Can you implement this?
Thx!

**Comment by id1945** [comment]
Your question is very good.  I will prioritize this issue for next update if is possible

**Comment by id1945** [comment]
@JimTudeski It works starting from version 1.2.1 👍

**Comment by JimTudeski** [comment]
what is  the property name or how enable this function?
