### ISSUE TITLE
default device

### ISSUE THREAD

**Issue by JimTudeski** [id1945/ngx-scanner-qrcode#14]
How can i "start" the camera with a default camera? The modul always use the front camera after starting but i would like to setup to start with another one (normal back with light).

**Comment by id1945** [comment]
@JimTudeski  
It works starting from version 1.2.1 👍

**Comment by JimTudeski** [comment]
hows working now? after i saved an ScannerQRCodeDevice.deviceId next time i call playDevice with this ID?

**Comment by JimTudeski** [comment]
what ScannerQRCodeConfig.deviceActive is? index of ScannerQRCodeDevice[] ?

**Comment by JimTudeski** [comment]
if i started with isAuto: true the camera don't read any qrcode

**Comment by id1945** [comment]
> what ScannerQRCodeConfig.deviceActive is? index of ScannerQRCodeDevice[] ?

It is the order of the devices Array

**Comment by id1945** [comment]
@JimTudeski  I will review a few remaining problems you have this weekend!
