### ISSUE TITLE
Video Feed is working as long as the mobile screen is pressed with thumb.

### ISSUE THREAD

**Issue by MaidaShahid** [id1945/ngx-scanner-qrcode#17]
Hi..
I'm facing an issue. I have built the application on 2 devices. On 1 device it is working fine but on the other device the video stream is working as long as i press/tap the screen. After i release the screen, the video stream gets stuck.

Kindly help if you know the issue

**Comment by MaidaShahid** [comment]
There is no issue in the code. It is working fine on the browser as well.
When i make a build of the project on the mobile. there is one device on which i face the issue on the other device it is working fine..
Wanted to know if there is any device limitation or any other issue related to the device

**Comment by id1945** [comment]
@MaidaShahid 
I really want to fix this but it's really hard to reproduce the error.  :disappointed_relieved:

**Comment by MaidaShahid** [comment]
https://github.com/MaidaShahid/myQRCode

Here is the source code. 
Kindly have a look

**Comment by MaidaShahid** [comment]
when i press the screen then logcat shows

2023-02-21 14:07:48.879 5107-5150/com.example.app E/GPUAUX: [AUX]GuiExtAuxCheckAuxPath:663: Null anb
2023-02-21 14:07:48.879 5107-5150/com.example.app E/GPUAUX: [AUX]GuiExtAuxCheckAuxPath:663: Null anb

while i stop pressing the screen then the logcat shows
2023-02-21 14:07:48.894 5107-5107/com.example.app I/ViewRootImpl@310fa4e[MainActivity]: ViewPostIme pointer 1

**Comment by id1945** [comment]
@MaidaShahid Can you record the operation on your device with an actual video?
