### ISSUE TITLE
Doesn't prompt for camera permissions on laptop

### ISSUE THREAD

**Issue by sam-lex** [id1945/ngx-scanner-qrcode#19]
This is related to #15 . Works on mobile, but on laptop it never prompts for camera permission.

If you follow the example given, nothing happens after pressing the "Start" button, no errors get printed on the console, so it just looked like nothing was happening...

Here's an "easy fix", get the camera permissions manually, this will activate your webcam, so I just immediately stop the stream.

Once I get the permission, and I go click on "Start", it works.

```typescript
export class QrScanViewComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
    navigator.mediaDevices.getUserMedia({video: true, audio: false})
      .then(stream => {
        stream.getTracks().forEach(track => track.stop());
      })
      .catch(err => {
        console.error('Error on get user media:', err);
      });
  }

}
```

Or you could just start the scanner immediately after you successfully got the permissions:
```typescript
export class QrScanViewComponent implements OnInit, AfterViewInit {

  @ViewChild(NgxScannerQrcodeComponent) scanner!: NgxScannerQrcodeComponent;

  constructor() { }

  ngOnInit(): void {
  }

  ngAfterViewInit(): void {
    navigator.mediaDevices.getUserMedia({video: true, audio: false})
      .then(stream => {
        // Since we're starting the scanner, we might not need to stop the streams... dunno "\o/"
        // stream.getTracks().forEach(track => track.stop());
        this.scanner.start();
      })
      .catch(err => {
        console.error('Error on get user media:', err);
      });
  }

}
```
If we start the scanner immediately though, I'm not quite sure we'll need to stop the streams before we start again, commenting out that line seems to work fine (and faster, as it doesn't need to stop/start again), just not sure if there's any issues doing that. From my quick test so far, it works ok. Stopping the scanner also stops the camera.

**Comment by id1945** [comment]
# Ohh!.  :1st_place_medal:  @sam-lex 
- It needs to get the list of available cameras and then continue to run a specified camera device according to the index of the existing device array. So it won't be as fast as your example is showing.  With the error on the laptop I need time to reproduce. 
- Thank you for your contribution.

**Comment by id1945** [comment]
@sam-lex I have updated to the new version. Please check again and let me know. Thank you!

**Comment by sam-lex** [comment]
@id1945 Hey, just got the time to test it, it's working perfectly now. Thanks!
