### ISSUE TITLE
Not working on safari

### ISSUE THREAD

**Issue by KarsusITA** [id1945/ngx-scanner-qrcode#20]
Hello, thank you for this useful plugin.

We have issue to make this work on ios/safari.
Simply seems to not start the scan. Works like a charm on android,

**Comment by KarsusITA** [comment]
Seems to be related with this topic
https://github.com/id1945/ngx-scanner-qrcode/issues/19#issue-1605723572

The user solution seems to fix the problem

**Comment by id1945** [comment]
@KarsusITA  I will try to fix this if I can reproduce this! Thank you ^^

**Comment by id1945** [comment]
@KarsusITA The new version has been patched. Please check it out!
