### ISSUE TITLE
Error on Ios: window.navigator.vibrate is not a function

### ISSUE THREAD

**Issue by chborntraeger** [id1945/ngx-scanner-qrcode#21]
When running an app on ios an error occurs: window.navigator.vibrate is not a function. 

https://caniuse.com/?search=vibrate

I think you should check the capabilities of the browser to prevent this error.

kind regards

**Comment by id1945** [comment]
@chborntraeger Okay.  
> I will fix this error as soon as possible.  If your project is having problems, you can set the input variable value to vibrate=0, it will disconnect itself and not cause code errors in your project anymore.  Thank you for early notification of this incident.
