### ISSUE TITLE
Mobile support on Android chrome

### ISSUE THREAD

**Issue by karanbedre** [id1945/ngx-scanner-qrcode#22]
My angular CLI version is 15 and I copied the same code from your example but it is not working on mobile.

**Comment by id1945** [comment]
@karanbedre What version do you use?

**Comment by karanbedre** [comment]
yes, the links you provided works on my mobile. but if i implement the same in angular project and check it on my mobile, it is not working. what might be the issue?

**Comment by david2242** [comment]
Can you show your code? Maybe we can help.

**Comment by karanbedre** [comment]
![qrcodehtml](https://user-images.githubusercontent.com/17941794/230825271-f73f8c9f-aa4b-4edf-8297-cdc3ee1eeccc.png)
![qrcodets](https://user-images.githubusercontent.com/17941794/230825278-f7d1d49c-40f1-46cd-8606-8f82dad0e760.png)

this are two html and ts files.
this are angular version in my project

 "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/material": "^15.2.1",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/router": "^15.1.0",

**Comment by karanbedre** [comment]
when I run on laptop browser, it works perfectly fine. I can select the device from the dropdown but where as in mobile, im not able to select any device. is it a mobile settings or any other issue

**Comment by id1945** [comment]
@karanbedre What library version are you using?
