### ISSUE TITLE
Issue with the wasm dependency

### ISSUE THREAD

**Issue by S-DWORD** [id1945/ngx-scanner-qrcode#23]
Hi, thanks for providing this code. I've used it for a QR-Code scanner with vs. 1.0.17 without any problems. Now I tried out the current version 1.2.6 and had the following issue when trying to start the scanner in my chrome-Browser:
platform-browser.mjs:564          GET http://<ip,port>/assets/wasm/index.js net::ERR_ABORTED 404 (Not Found)
Refused to execute script from 'http://<ip,port>/assets/wasm/index.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
core.mjs:7739 ERROR Error: Uncaught (in promise): ReferenceError: zbarWasm is not defined
ReferenceError: zbarWasm is not defined

Any idea how to solve this problem? 
Thanks in advance for your response!

**Comment by id1945** [comment]
@S-DWORD Please add config for angular.json
```JavaScript
{
  "architect": {
    "build": {
      "options": {
        "assets": [
          {
            "glob": "**/*",
            "input": "node_modules/ngx-scanner-qrcode/wasm/",
            "output": "./assets/wasm/"
          }
        ]
      }
    }
  }
}
```

**Comment by S-DWORD** [comment]
Thanks, as in most cases the problem was in front of the computer... After adding the configurations I had to delete the cash in my Webbrowser. A clean restart worked.
