### ISSUE TITLE
Set default to back camera for ios/android

### ISSUE THREAD

**Issue by heyjudemaldicas** [id1945/ngx-scanner-qrcode#27]
Is there any way to use the default back camera of any ios and android devices? The device index seems to vary for every mobile devices and also depends on how may back cameras are there.

**Comment by id1945** [comment]
@heyjudemaldicas Yes. If the device index it does not reflect correctly in many cases, I will check again and find a solution.

**Comment by SamTomashi** [comment]
I am also trying to achieve the same. 
The library is very good and simple to use but I am unable to use the back-camera.
Which in my opinion will provide a better user experience.
Any update on this?
@id1945 what do you mean by "_If the device index it does not reflect correctly in many cases_"?

**Comment by id1945** [comment]
@SamTomashi  I mean @Input() deviceActive it is index by array of cameras present on device

```typescript
// Cameras
const cameraArr = [cameraBefore, cameraAfter] // deviceActive: 0, 1
// In project
[deviceActive]="1"
```

**Comment by SamTomashi** [comment]
@id1945 I have tried to set the `[deviceActive]="1"` and `[deviceActive]= 1` but it still using the front-camera.
Where should put the `const cameraArr = [cameraBefore, cameraAfter]`?

**Comment by id1945** [comment]
@SamTomashi  
```javascript
const cameraArr = [cameraBefore, cameraAfter]
// This is just an example code to explain to you!
```

**Comment by SamTomashi** [comment]
I see, thank you.

**Comment by SamTomashi** [comment]
Should we expect an update anytime soon solving the back camera issue?

**Comment by id1945** [comment]
> Chúng ta nên mong đợi một bản cập nhật sớm giải quyết vấn đề về camera sau không?

I will try to find the error and fix it as quickly as possible. Thank you for your interest and use of this library @@

**Comment by id1945** [comment]
@SamTomashi I will try to find the error and fix it as quickly as possible. Thank you for your interest and use of this library @@

**Comment by ezequiel88** [comment]
Is same problem. solution?

**Comment by id1945** [comment]
@ezequiel88 Are you currently using an android or ios phone?

**Comment by id1945** [comment]
@ezequiel88  I have updated the new version 1.2.9 hope to solve the problems you are having. Please check it out and let me know! Thank you

**Comment by ranalav** [comment]
@id1945 can please guide me to implement default back main camera, currently getting two many options
