### ISSUE TITLE
Default Back camera not working for Samsung galaxy tab S8

### ISSUE THREAD

**Issue by goku7995** [id1945/ngx-scanner-qrcode#29]
Hi the qr scanner is really wonderful and its working great. But I have one small issue in Samsung galaxy tab s8. For this device it doesn't open the back camera as default. It shows two front camera I attached the screenshot for your reference can you pls try to resolve this issue asap. Once again thankyou for your help.
![16830209050222220304079894518414](https://user-images.githubusercontent.com/36992970/235634909-38c8cd33-95de-48c4-9084-ff2a6bcd5b15.jpg)

**Comment by id1945** [comment]
Yeah 😁. I will check it

**Comment by id1945** [comment]
@goku7995  I have updated the new version 1.2.9 hope to solve the problems you are having. Please check it out and let me know! Thank you
