### ISSUE TITLE
Multiple scan issue

### ISSUE THREAD

**Issue by eTolgaKaradogan** [id1945/ngx-scanner-qrcode#32]
Hi,

Basically I want to scan only one QR Code and close the dialog window. When I scanned the QR Code its scans multiple times, may be 7-10 times. 

I just want to scan one time every time dialog window opens. Can u help me?

Thanks in advance.

**Comment by id1945** [comment]
@eTolgaKaradogan I have updated the new version on this issue check it now.

**Comment by eTolgaKaradogan** [comment]
> @eTolgaKaradogan I have updated the new version on this issue check it now.

Hi,

I checked the new version but can not find the solution. 

Basically, there will be notification when QR Code is scanned. But when I scan the QR Code there are 7-8 notifies. Also, my code is like that: 

 const data = e[0].value;
 
 So what I am trying to do is with just one data.

**Comment by id1945** [comment]
@eTolgaKaradogan 
- Pls flow https://stackblitz.com/edit/angular-ngx-scanner-qrcode
- You notice this handler function will help you stop the camera

```typescript
  public onEvent(e: ScannerQRCodeResult[], action?: any): void {
    e && action && action.pause();  // Here!
    console.log(e);
  }
```
