### ISSUE TITLE
Auto focus/zoom / high resolution does not work

### ISSUE THREAD

**Issue by maerni** [id1945/ngx-scanner-qrcode#35]
We want to use the ngx-scanner-qrcode.

Now we have the problem, that it does not work with small QR Codes (i.e. 3x3mm).

With normal or big QR Codes it works.

We think, the problems are that the auto focus/zoom does not work.

How we can activate auto focus/zoom and a higher resolution?

Thanks very much.

**Comment by id1945** [comment]
@maerni This problem is really difficult to solve. I will take a lot of time to learn and come up with an idea to solve it.

**Comment by maerni** [comment]
@id1945 okey, would be very nice, if you would have an idea to solve this ;-)

**Comment by id1945** [comment]
@maerni I have provided additional parameters to reduce the size when the camera takes photos. You can select the file and go to the camera. Here the camera allows you to zoom in.
![Capture](https://github.com/id1945/ngx-scanner-qrcode/assets/40824445/ae7810d3-9891-4845-9919-8ce9d9b1d548)
