### ISSUE TITLE
Facing problem for switching the back-camera

### ISSUE THREAD

**Issue by sidharth-aguaws** [id1945/ngx-scanner-qrcode#36]

**Comment by id1945** [comment]
@sidharth-aguaws 
Are you sure you did the same as the code below?

```typescript
public handle(action: any, fn: string): void {
    const playDeviceFacingBack = (devices: ScannerQRCodeDevice[]) => {
         const device = devices.find(f => (/back|rear|environment/gi.test(f.label)));
         action.playDevice(device ? device.deviceId : devices[0].deviceId);
    }

    if (fn === 'start') {
         action[fn](playDeviceFacingBack).subscribe((r: any) => console.log(fn, r), alert);
    } else {
         action[fn]().subscribe((r: any) => console.log(fn, r), alert);
    }
}
```

```typescript
const device = devices.find(f => (/back|rear|environment/gi.test(f.label))); 
```

**Comment by sidharth-aguaws** [comment]
@id1945 
yes also implement this but so, there is 2 problem 1st one is that switching camera is not happened and if my camera toggled it will not detect my qr code result and if we switch camera to front camera and can again same qr code it will scan the result

``public handle(action: any, fn: string): void {
const playDeviceFacingBack = (devices: ScannerQRCodeDevice[]) => {
const device = devices.find(f => (/back|rear|environment/gi.test(f.label)));
action.playDevice(device ? device.deviceId : devices[0].deviceId);
}
if (fn === 'start') {
action[fn](https://github.com/id1945/ngx-scanner-qrcode/issues/playDeviceFacingBack).subscribe((r: any) => console.log(fn, r), alert);
} else {
action[fn](https://github.com/id1945/ngx-scanner-qrcode/issues/36).subscribe((r: any) => console.log(fn, r), alert);
}
}
