### ISSUE TITLE
Permission Camera Smartphone

### ISSUE THREAD

**Issue by larnerdoj** [id1945/ngx-scanner-qrcode#37]
**Hello! How are you!**
I'm having trouble trying to scan using my **smartphone camera**.

When opening the demo, I noticed the same problem.

Is it possible to enable **camera permission** on smartphones?

Thank you very much for making the library available

**Comment by larnerdoj** [comment]
Verifiquei que a permissão para acessar a câmera estava desabilitada no aplicativo do chrome.

Habilitei a permissão lá e funcionou!

Muito obrigado!

**Comment by DrDrThein** [comment]
did you figure it out ?
