### ISSUE TITLE
CSS documentation

### ISSUE THREAD

**Issue by Stefke-Novo** [id1945/ngx-scanner-qrcode#38]
Hi, could someone provide me information about changing the components with CSS ? I use 1.5.8 version of the app in angular. I've implemented it but I couldn't change anything. Thank you for your time and effort.

**Comment by id1945** [comment]
@Stefke-Novo Want to tweak the css yourself? But unlucky for you because there are some things that need to add css right after creating the element. 
`Please be more specific so I can find solution for the upcoming release!`

**Comment by Stefke-Novo** [comment]
Yup, here's the problem. This menu is displayed absolute.
![image](https://github.com/id1945/ngx-scanner-qrcode/assets/72997632/e8a2481b-5869-4de9-a07d-d40951ff5ad6)
After reaching the page where I put QR scanner, something begins to be odd.
The first thing I see after implementation that view is made sticky position or in something similar as in picture bellow.
![image](https://github.com/id1945/ngx-scanner-qrcode/assets/72997632/74ce3678-ad71-4065-81a4-de7d5dffee8c)
After that, I wanted to change the elements to be in display:flex. In this particular instance I see that overlay component has to be there for some reason and honestly I don't know why.
![image](https://github.com/id1945/ngx-scanner-qrcode/assets/72997632/e63eeabb-59d2-4ae8-9928-85abf29b5bd9)
Div with class "origin-overlay" does not have any height when is everything displayed with "box-sizing:border-box;"
Now, other 2 components with classes "origin-canvas" and "origin-video", even they now have position:relative (I gave the css on browser the components), I can't still make the components go under my menu like in picture bellow:
![image](https://github.com/id1945/ngx-scanner-qrcode/assets/72997632/f4b6193d-dbfa-499d-9a45-41f5b60555bf)
For the reasons I tried to see if I could find any documentation to fix the issue but I didn't find. I'll be glad to help as well improving the app because this is my graduation project.
Here's link to the project if you want to see how the situation really is:
https://github.com/Honey-beer-application/honey-beer-app
Just one note: github-pages is not updated because it's full-stack application.

**Comment by Stefke-Novo** [comment]
@id1945 Thank you for your time and help 😄💯

**Comment by id1945** [comment]
@Stefke-Novo
```css
.navigation {
    z-index: 1;  /* add this */
}
```

**Comment by id1945** [comment]
@Stefke-Novo
```css
.navigation {
    z-index: 1;  /* add this one */
}
```
