### ISSUE TITLE
Camera screen is too stretched

### ISSUE THREAD

**Issue by Guts39** [id1945/ngx-scanner-qrcode#4]
Hi, i'm trying to put the camera on full screen on mobile device, it works but the canvas is too stretched on full screen. 

How could I edit the canvas size without the vertical scroll ? 

I tried this : 

` 
<ngx-scanner-qrcode [config]="configScanner" #action="scanner" class="scanner-dialog" (event)="getReference($event)"></ngx-scanner-qrcode>

public configScanner = {
    frame: { width: '100%', height: '100%' },
  };`

**Comment by id1945** [comment]
Please upgrade new version! Thanks
