### ISSUE TITLE
Can this implemented on Ionic Capacitor ?

### ISSUE THREAD

**Issue by josephvoxone** [id1945/ngx-scanner-qrcode#40]
I tried it on the web and it worked perfectly, but I encountered a problem when implementing it on Ionic Angular. It seems like the camera is stuck and doesn't want to read QR codes or barcodes. Can you help me?

**Comment by id1945** [comment]
@josephvoxone 
Camera works based on navigator.mediaDevices.getUserMedia()
So you need to check if it works on that device?

**Comment by josephvoxone** [comment]
Actually, the camera was working perfectly, somehow the video camera just stuck like froze and work again when detects the barcode or QR code.

**Comment by id1945** [comment]
@josephvoxone This is a difficult problem.

**Comment by josephvoxone** [comment]
Okay, thank you. 👍 I will find out my self
