### ISSUE TITLE
Camera not working on localhost

### ISSUE THREAD

**Issue by alexeaztman** [id1945/ngx-scanner-qrcode#44]
I wanted to share a heads-up regarding a camera issue I encountered on localhost. It turns out the camera wasn't functioning as expected, possibly due to certain browsers hesitating to grant camera access on localhost without a valid SSL certificate.

For those who might encounter this

1. Run your Angular development server using
   ```
   ng serve --ssl true
   ```

2. Additionally, remember to include the `--watch` flag if needed.

Perhaps, it could be a helpful addition to the documentation as well.

@id1945, your thoughts on documenting this?

**Comment by id1945** [comment]
@alexeaztman I would like to acknowledge!
It will be useful for those who are facing the same problem as above.
Thank you for this contribution.
