### ISSUE TITLE
Unable to change the default camera

### ISSUE THREAD

**Issue by sureshmohan251** [id1945/ngx-scanner-qrcode#45]
I have the below code to change the default camera but Back facing camera is not set as default by playDeviceFacingBack function

`public enableScanner() {
        this.scannerEnabled = !this.scannerEnabled;
        if (this.scannerEnabled) {
            const playDeviceFacingBack = (devices: any[]) => {
                // front camera or back camera check here!
                console.log(devices);
                const device = devices.find((f) =>
                  /back|environment|rear/gi.test(f.label)
                ); // Default Back Facing Camera
                this.action.playDevice(device ? device.deviceId : devices[0].deviceId);
              };
              this.action["start"](playDeviceFacingBack).subscribe(
                (r: any) => console.log('start', r),
                //alert
              );
            this.action.start();
        } else {
            this.action.stop();
        }
    }
`

**Comment by id1945** [comment]
@sureshmohan251 It is not an error please check devices
