### ISSUE TITLE
isBeep don`t work

### ISSUE THREAD

**Issue by AlexTixaskiy** [id1945/ngx-scanner-qrcode#46]
I use isBeep = false but there is still sound. How to turn off the sound?
angular version 16.2.4

**Comment by id1945** [comment]
@AlexTixaskiy Can you post this bug on stackblitz?

**Comment by AlexTixaskiy** [comment]
@id1945 I can not. I added a link to the repository https://github.com/AlexTixasky/qr-reader-angular

**Comment by AlexTixaskiy** [comment]
@id1945 i can not. I added lint to repository https://github.com/AlexTixaskiy/qr-reader-angular

**Comment by AlexTixaskiy** [comment]
@id1945 https://stackblitz.com/edit/stackblitz-starters-uee4mm?file=src%2Freader%2Freader.component.ts

**Comment by id1945** [comment]
@AlexTixaskiy Thank you!

**Comment by id1945** [comment]
@AlexTixaskiy Done! Pls check version 1.6.4 for Angular 16

**Comment by AlexTixaskiy** [comment]
@id1945 It is work. Thanks.
