### ISSUE TITLE
Ngx-scanner-qrcode is not a known element

### ISSUE THREAD

**Issue by MichalPisanczuk** [id1945/ngx-scanner-qrcode#5]
After installation, when i try to use qrcode scanner in html file getting ngx-scanner-qrcode is not known element
package.json file:
"@ angular / core": "^ 14.0.0"
"ngx-scanner-qrcode": "^ 1.0.25"
The NgxScannerQrcodeModule is imported in app.module.ts

**Comment by id1945** [comment]
=> app.module.ts <=
Make sure the file is saved
