### ISSUE TITLE
Upgrade to Angular 17

### ISSUE THREAD

**Issue by dave0688** [id1945/ngx-scanner-qrcode#50]
The library has `peerDependencies` from Angular 16:

```
"peerDependencies": {
    "@angular/common": "^16.0.0",
    "@angular/core": "^16.0.0"
},
```

which makes it impossible to use this library with Angular 16. 
Is it possible to upgrade to Angular 17?

Thanks!

**Comment by daiduongdjv** [comment]
@dave0688 I will update to version 17 as soon as possible.
For now you can use "npm install ngx-scanner-qrcode -f"

**Comment by jasonc624** [comment]
Same i need a scanner

**Comment by nik2208** [comment]
u should be able to add the following

```json
{
"other-att":{...},
"overrides": {
    "ngx-scanner-qrcode": {
      "@angular/common": "^17.0.9",
      "@angular/core": "^17.0.9"
    }
  }
}
```
at the bottom of ur package.json

**Comment by id1945** [comment]
@dave0688 @jasonc624 @nik2208 Please upgrade to the latest version.

**Comment by PinkPanther2000** [comment]
I installed the latest version but it looks like the peerDependencies to Angular 16 still exists. Unable to get it working on Angular 17
![image](https://github.com/id1945/ngx-scanner-qrcode/assets/159172675/15cbd474-d3bc-4bc4-81af-3dd8a6ab27fb)
