### ISSUE TITLE
NgxScannerQrcodeModule source code (WASM)

### ISSUE THREAD

**Issue by Salamek** [id1945/ngx-scanner-qrcode#53]
Hi, i fail to find source code for NgxScannerQrcodeModule in this repo? Or i'm just blind? :-)

**Comment by daiduongdjv** [comment]
@Salamek It has been set to private.

**Comment by Salamek** [comment]
So this LGPL project has proprietary component?

**Comment by id1945** [comment]
@Salamek Not necessarily so. I have set a free license for users. I just don't want others to participate in developing with me.
