### ISSUE TITLE
Dependencies not working with Angular 17.0.6

### ISSUE THREAD

**Issue by IngoM21** [id1945/ngx-scanner-qrcode#56]
npm WARN Conflicting peer dependency: @angular/common@17.0.0
npm WARN node_modules/@angular/common
npm WARN   peer @angular/common@"^16.0.0 || 17.0.0 || 18.0.0" from ngx-scanner-qrcode@1.6.8
npm WARN   node_modules/ngx-scanner-qrcode
npm WARN     ngx-scanner-qrcode@"^1.6.8" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ngx-scanner-qrcode@1.6.8
npm WARN Found: @angular/core@17.0.6
npm WARN node_modules/@angular/core
npm WARN   @angular/core@"17.0.6" from the root project
npm WARN   24 more (@angular/animations, @angular/cdk, @angular/common, ...)

**Comment by daiduongdjv** [comment]
@IngoM21 pls update new version

**Comment by Chreggii** [comment]
Which new version do you mean? The main branch is still on Angular 16: https://github.com/id1945/ngx-scanner-qrcode/blob/master/package.json
