### ISSUE TITLE
Ability to scan inverted (white on black) codes

### ISSUE THREAD

**Issue by Romanizat** [id1945/ngx-scanner-qrcode#63]
I use your library to activate video scanning from a device and it's active until it scans the QR code, and it works great, thanks!

But...

I require scanning of inverted QR codes (white code on black background), and I've been trying all kinds of hacks to get it to work, but apparently it only registers black code on white background.

I have been trying to invert the input video, but to no avail.

**Comment by id1945** [comment]
@Romanizat  Thank you for raising the above issue. Currently I don't have a way to solve this problem.

**Comment by Romanizat** [comment]
@id1945 Thank you for the reply.

If it is any help, I have found [jsQR](https://github.com/cozmo/jsQR) and am using it in my project now for scanning inverted and normal QR codes.

This is a pure javascript library for which i need to make a wrapper for the webcam and mobile devices that already exist in your library.

I don't know which underlying library you are using for the scanning, but if you can just replace it with this one, or try both, I think it will solve the issue and provide a better expansion to your library.

All the best!
