### ISSUE TITLE
Stop the scanning without stoping the video.

### ISSUE THREAD

**Issue by danielfsc** [id1945/ngx-scanner-qrcode#65]
There is a way to stop the qr-code scanning without stop the video?

I need to scan a QR-code and then scan another object with my own code. My goal is to save hardware resources because my code is a little bit expensive. I could put another video element, but if there is a way to stop the qrcode scaning, will be helpful.

Thank you the package, it's very helpful.

**Comment by id1945** [comment]
@danielfsc I take note of your comments. Maybe it will be added in the next version.

**Comment by danielfsc** [comment]
If You share the code I can do It for You.

**Comment by id1945** [comment]
@danielfsc Version 1.7.2 and 1.7.3 already have the feature you want. Please upgrade your version now.
