### ISSUE TITLE
Error importing NgxScannerQrcodeModule on Angular 14

### ISSUE THREAD

**Issue by yordanisperez** [id1945/ngx-scanner-qrcode#7]
Hi, I am adding your `NgxScannerQrcodeModule` npm package to my angular project.

When I import in my `app.module.ts`

```
...
import { NgxScannerQrcodeModule } from 'ngx-scanner-qrcode';

@NgModule({
  declarations: [AppComponent, ErrorPageComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    BrowserAnimationsModule,
    NgxScannerQrcodeModule,
  ],
...
```

and compile the application I receive the following error.

```
Error: node_modules/ngx-scanner-qrcode/lib/ngx-scanner-qrcode.component.d.ts:151:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.
s between 7 and 8 type arguments.
151     static ɵcmp: i0.ɵɵComponentDeclaration<NgxScannerQrcodeComponent, "ngx-scanner-qrcode", ["scanner"], { "src": "src"; "isAuto": "isAuto"; 
"config": "config"; "text": "text"; "style": "style"; "frame": "frame"; "medias": "medias"; }, { "event": "event"; "error": "error"; }, never, ["*"], false, never>;
```
I have checked your `package.json` in
https://stackblitz.com/edit/angular-ngx-scanner-qrcode?file=package.json
and it is very similar to my project.
```
...
"dependencies": {
    "@angular-material-components/datetime-picker": "^8.0.0",
    "@angular/animations": "~14.2.5",
    "@angular/cdk": "^14.2.4",
    "@angular/common": "~14.2.5",
    "@angular/compiler": "~14.2.5",
    "@angular/core": "~14.2.5",
    "@angular/flex-layout": "^14.0.0-beta.40",
    "@angular/forms": "~14.2.5",
    "@angular/material": "^14.2.4",
    "@angular/platform-browser": "~14.2.5",
    "@angular/platform-browser-dynamic": "~14.2.5",
    "@angular/router": "~14.2.5",
    "leaflet": "^1.8.0",
    "ng-recaptcha": "^10.0.0",
    "ngx-scanner-qrcode": "^1.0.26",
    "rxjs": "~7.5.7",
    "sweetalert2": "^11.4.4",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.2.5",
    "@angular/cli": "~14.2.5",
    "@angular/compiler-cli": "~14.2.5",
    "@types/jasmine": "~4.3.0",
    "@types/leaflet": "^1.7.10",
    "@types/node": "^18.8.4",
    "jasmine-core": "~4.4.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.8.4"
  }
...
```
Perhaps I have overlooked something important, I have not even used its components.

Any help will be greatly appreciated, I really like the QR reading approach you have given to your module.

Greetings, Yordanis.

**Comment by id1945** [comment]
@yordanisperez Can you publish your faulty project to github? I need to test it to see why it's error!

**Comment by yordanisperez** [comment]
I'm sorry I didn't reply to you earlier.

My project is not for public use but instead I simplified a project which also throws the mentioned error.

https://github.com/yordanisperez/qrapp

**Comment by yordanisperez** [comment]
Let me add that my work environment is windows. Perhaps the reason why this error is happening only to me could happen.

Angular CLI: 14.2.10
Node: 16.13.1
Package Manager: npm 8.2.0
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

**Comment by chibisuke** [comment]
This happens when you build a component library using angular 15, and try to use it in angular 14. 
They added a 9th parameter to ɵɵComponentDeclaration in Angular 15 to allow for adding of the HostDirectives. Even though this type parameter gets set to "never" if no HostDirectives are used in the @Component directive, angular 14 can't deal with this. The other way around should work (using angular 14 components in angular 15).

**Comment by id1945** [comment]
I will update them again!

**Comment by id1945** [comment]
@yordanisperez @chibisuke Version 1.0.28-RTM.14 support for Angular 14 has been release!

**Comment by id1945** [comment]
#### I have updated several versions including Angular14 👍 
  
<table>
  <tr>
    <th colspan="2">Support versions</th>
  </tr>
  <tr>
    <td>Angular 15</td>
    <td>1.0.30</td>
  </tr>
  <tr>
    <td>Angular 14</td>
    <td>1.0.29</td>
  </tr>
  <tr>
    <td>Angular 9</td>
    <td>1.0.28</td>
  </tr>
  <tr>
    <td>Angular 8</td>
    <td>1.0.17 ~ 1.0.25</td>
  </tr>
</table>

**Comment by yordanisperez** [comment]
Thank you very much, a little late. I have updated all my project to @angular15.0.1 to be able to use their QR libraries.

It has taken me several days to perform the migration, I hope it's worth it.

Thank you very much, someone else will surely appreciate it.

My greetings.
