### ISSUE TITLE
Excluding types from camera itself

### ISSUE THREAD

**Issue by RistoRoosipuu** [id1945/ngx-scanner-qrcode#73]
Is it possible to somehow pass a blacklist or pass some kind of flag to force the camera to completely ignore some of the scannable objects?

In my case, I would like for it to scan all the supported barcodes but NOT the qr-code. 
Or does the scanner scan everything it can find and only the results can be filtered?

**Comment by daiduongdjv** [comment]
@RistoRoosipuu Please wait for the next update!

**Comment by id1945** [comment]
@RistoRoosipuu Please use the latest version 1.7.2 or 1.7.3
