### ISSUE TITLE
Property '"src"' is incompatible with index signature.

### ISSUE THREAD

**Issue by MyVeriMed-2023** [id1945/ngx-scanner-qrcode#75]
**I install the package and im, getting compile error** 
Error: node_modules/ngx-scanner-qrcode/lib/ngx-scanner-qrcode.component.d.ts:156:106 - error TS2344: Type '{ src: { alias: "src"; required: false; }; fps: { alias: "fps"; required: false; }; vibrate: { alias: "vibrate"; required: false; }; decode: { alias: "decode"; required: false; }; isBeep: { alias: "isBeep"; required: false; }; config: { ...; }; constraints: { ...; }; canvasStyles: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"src"' is incompatible with index signature.
    Type '{ alias: "src"; required: false; }' is not assignable to type 'string'.

**Comment by id1945** [comment]
@MyVeriMed-2023 What version of angular are you using?
