### ISSUE TITLE
Angular 19: NgxScannerQrcodeModule does not appear to be an NgModule class

### ISSUE THREAD

**Issue by spock123** [id1945/ngx-scanner-qrcode#76]
After upgrading to V19, the compiler throws this error:

`✘ [ERROR] TS-996002: 'NgxScannerQrcodeModule' does not appear to be an NgModule class. [plugin angular-compiler]`

Using version 1.7 of this library.
Any help greatly appreciated.

**Comment by id1945** [comment]
@spock123 Yesterday 11/23/2024 and today I am upgrading the version and adding some new features. Please wait patiently.

**Comment by spock123** [comment]
@id1945  whoa you're awesome! thank you

**Comment by id1945** [comment]
@spock123 You can use the latest version now 🥇
