### ISSUE TITLE
Suggestion: Stop after completing to read the QR code

### ISSUE THREAD

**Issue by wjun20314** [id1945/ngx-scanner-qrcode#8]
QR scanner process was running good at my program. Your library was very good. 👍  Thanks you.

But one things will recommend you to fix the library is after the scanner capture the QR data and it will close the scanning process **automatically**. To avoid `async` keep hitting the backend process non-stop within a few seconds. For example, If the backend process is to call API to database or server, it will create huge burden to your server.

For example situation I faced as below screen, I have to click the button to stop the scanner if not it will continue to trigger the `(event)="scanComplete(valueObj = $event)"` non-stop.
![image](https://user-images.githubusercontent.com/18068704/204501867-4a20d4d4-498b-4d70-8628-dca47d58016d.png)

**Mypage.html**
```
<ngx-scanner-qrcode #action="scanner" (event)="scanComplete(valueObj = $event)" class="scanSize"></ngx-scanner-qrcode>
      
<p class="data">{{ action.data | async }}</p>
<p *ngIf="action.isLoading">⌛ Loading...</p>

<button class="btn btn-primary col-3" (click)="action.isStart ? action.stop() : action.start()">
  {{action.isStart ? 'Stop' : 'Scan QR'}}
</button>
```

**Mycomponent.ts**
```
scanComplete(data: any) {
    console.log("data capture:: " + data);
}
```

Hopefully my advice will help you to build better Angular library :)

**Comment by id1945** [comment]
@wjun20314  :+1: 
Great comments. I will update it to the upcoming version.

**Comment by id1945** [comment]
#### Hi @wjun20314 all versions have supported the above function. It is set by the isAlwaysEmit variable. Please close this issue if it's done.!
  
<table>
  <tr>
    <th colspan="2">Support versions</th>
  </tr>
  <tr>
    <td>Angular 15</td>
    <td>1.0.33</td>
  </tr>
  <tr>
    <td>Angular 14</td>
    <td>1.0.32</td>
  </tr>
  <tr>
    <td>Angular 9</td>
    <td>1.0.31</td>
  </tr>
</table>
