### ISSUE TITLE
[Violation] 'requestAnimationFrame' handler took 

### ISSUE THREAD

**Issue by yordanisperez** [id1945/ngx-scanner-qrcode#9]
Dear DaiDH

I have found other unexpected behavior.
I have only been able to verify it in the chrome browser console, even in its version published at 
https://stackblitz.com/edit/angular-ngx-scanner-qrcode?file=src/app/app.component.html

I use `isAuto:true, isAlwaysEmit: false,` in config.
`.ts onEvent`
```
public onEvent(action: any, e: any): void {
    console.log(action);
    action['stop']().subscribe(() => {
      this.scanerQr = false;  // This is use for drop of DOM scanner 
      this.refChangeDetect.markForCheck();
    }, console.error);
    console.log('QR', e);
  }
```
`.html`
```
  <ng-container *ngIf="scanerQr">
        <ngx-scanner-qrcode 
           #action="scanner"   
           [config]="config" 
           (event)="onEvent(action,$event)" 
          (error)="onError($event)">
       </ngx-scanner-qrcode>
       <!-- Loading -->
        <p *ngIf="action.isLoading">⌛ Loading...</p>
 </ng-container>
```

`[Violation] 'requestAnimationFrame' handler took <N>ms`
![imagen](https://user-images.githubusercontent.com/83768493/205689658-9e240049-4810-4f16-b2f0-5f25dc359dbc.png)

It seems that the component is not completely destroyed once it is removed from the DOM.

That is, even if the component is removed from the DOM, it continues to throw these warnings.

Which I don't think should happen, even though my machine is slow and that's the reason for the warning, once the component is removed from the DOM it shouldn't keep throwing these warnings.

My greetings

**Comment by yordanisperez** [comment]
Even if you change the path in the browser, the component is not destroyed.

Keep throwing the warning as long as you don't reload the browser.

**Comment by id1945** [comment]
@yordanisperez I will research and resolve this issue in the next few days :wink:
Thank for your issue.

**Comment by yordanisperez** [comment]
Whoops, what am I supposed to do with this commit  https://github.com/id1945/ngx-scanner-qrcode/commit/a143ec438799ab78ef7c6f7d9eb2975906f76192?

Excuse my lack of experience, if I should try something I would like to know.

I already saw that you have been working on this feature, if I can do anything to help you that I can, just let me know.

Greetings yordanis.

**Comment by id1945** [comment]
@yordanisperez This bug is fixed from version 1.0.35. You can test and use it right now!  :wink:

**Comment by id1945** [comment]
#### I have updated the latest patch update for angular 9 to 15. You can use them right now! :hugs:

<table>
  <tr>
    <th colspan="2">Support versions</th>
  </tr>
  <tr>
    <td>Angular 15</td>
    <td>1.0.38</td>
  </tr>
  <tr>
    <td>Angular 14</td>
    <td>1.0.37</td>
  </tr>
  <tr>
    <td>Angular 9</td>
    <td>1.0.36</td>
  </tr>
  <tr>
    <td>Angular 8</td>
    <td>1.0.25</td>
  </tr>
</table>

**Comment by yordanisperez** [comment]
Perfect.
I am very grateful to you, thanks to your work my application works correctly.

Congratulations
